In [1]:
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.cluster import MiniBatchKMeans
import numpy as np
from PIL import Image
import sys
import warnings 

warnings.filterwarnings(action='ignore')

In [2]:
fp = open(r"C:\pyml_scripts\chapter08_kmeans\shutterstock.jpg","rb")
im = Image.open(fp)
m,n = im.size

print(m,n)

1000 667


In [3]:
data = []
for i in range(m):
    for j in range(n):
        tmp = []
        x,y,z = im.getpixel((i,j))
        tmp.append(x/255.0)                  #R 
        tmp.append(y/255.0)                  #G
        tmp.append(z/255.0)                  #B
        data.append(tmp)

fp.close

data1 = np.array(data)

In [4]:
type(data1)

numpy.ndarray

In [5]:
data1[0]

array([0.40392157, 0.64705882, 0.88627451])

In [6]:
data1.size

2001000

In [7]:
KM2=KMeans(n_clusters=2)
KM2.fit(data1)

KMeans(n_clusters=2)

In [8]:
KM2.cluster_centers_
f_center = KM2.cluster_centers_
center=[]

for line in f_center:
    tmp = []
    for x in line:
        tmp.append(int(float(x)*255))
    center.append(tuple(tmp))

In [9]:
center

[(73, 76, 76), (155, 171, 172)]

In [10]:
f_center

array([[0.28771648, 0.30030283, 0.30175517],
       [0.60838827, 0.67419065, 0.67523474]])

In [11]:
KM2.labels_

array([1, 1, 1, ..., 0, 0, 0])

In [12]:
pic_new = Image.new("RGB",(m,n))
i = 0
for line in KM2.labels_:
    index_n = int(line)
    pic_new.putpixel((int(i/n),int(i%n)),center[index_n])
    i = i + 1


pic_new.save(r"c:\pyml_scripts\chapter08_kmeans\KM2.jpg","JPEG")

In [13]:
KM3=KMeans(n_clusters=3)
KM3.fit(data1)
KM3.cluster_centers_
f_center = KM3.cluster_centers_
center=[]

for line in f_center:
    tmp = []
    for x in line:
        tmp.append(int(float(x)*255))
    center.append(tuple(tmp))
    
pic_new = Image.new("RGB",(m,n))
i = 0
for line in KM3.labels_:
    index_n = int(line)
    pic_new.putpixel((int(i/n),int(i%n)),center[index_n])
    i = i + 1


pic_new.save(r"c:\pyml_scripts\chapter08_kmeans\KM3.jpg","JPEG")

In [14]:
KM20=KMeans(n_clusters=20)
KM20.fit(data1)
KM20.cluster_centers_
f_center = KM20.cluster_centers_
center=[]

for line in f_center:
    tmp = []
    for x in line:
        tmp.append(int(float(x)*255))
    center.append(tuple(tmp))
    
pic_new = Image.new("RGB",(m,n))
i = 0
for line in KM20.labels_:
    index_n = int(line)
    pic_new.putpixel((int(i/n),int(i%n)),center[index_n])
    i = i + 1


pic_new.save(r"c:\pyml_scripts\chapter08_kmeans\KM20.jpg","JPEG")

In [15]:
miniKM20=MiniBatchKMeans(n_clusters=20) #batch_size=1024
miniKM20.fit(data1)
miniKM20.cluster_centers_
f_center = miniKM20.cluster_centers_
center=[]

for line in f_center:
    tmp = []
    for x in line:
        tmp.append(int(float(x)*255))
    center.append(tuple(tmp))
    
pic_new = Image.new("RGB",(m,n))
i = 0
for line in miniKM20.labels_:
    index_n = int(line)
    pic_new.putpixel((int(i/n),int(i%n)),center[index_n])
    i = i + 1


pic_new.save(r"c:\pyml_scripts\chapter08_kmeans\miniKM20.jpg","JPEG")