In [1]:
import pandas as pd
from sklearn import tree
import numpy as np
import pydotplus #pip install pydotplus

import warnings
warnings.filterwarnings('ignore')  #不要顯示警告訊息,讓畫面比較乾淨

In [2]:
df = pd.read_csv(r'c:\pyml_scripts\chapter05_decisiontree\weather.csv',names=['Outlook','Temp','Humidity','Windy','Play'])

In [3]:
df.head()

Outlook  Temp Humidity  Windy Play
0     sunny   hot     high  False   No
1     sunny   hot     high   True   No
2  overcast   hot     high  False  Yes
3      rain  mild     high  False  Yes
4      rain  cool   normal  False  Yes

In [4]:
df.describe()

Outlook  Temp Humidity  Windy Play
count       14    14       14     14   14
unique       3     3        2      2    2
top      sunny  mild     high  False  Yes
freq         5     6        7      8    9

In [12]:
#0表示晴天,1表示多雲,2表示雨天
df.Outlook[df["Outlook"]=='Sunny']=0
df.Outlook[df["Outlook"]=='Overcast']=1
df.Outlook[df["Outlook"]=='Rainy']=2

#0表示低溫,1表示舒適溫度,2表示高溫
df.Temp[df["Temp"]=='Cool']=0
df.Temp[df["Temp"]=='Mild']=1
df.Temp[df["Temp"]=='Hot']=2

#0表示一般濕度,1表示高濕度
df.Humidity[df["Humidity"]=='Normal']=0  
df.Humidity[df["Humidity"]=='High']=1

#0表示無風,1表示有風
df["Windy"]=df["Windy"].apply(lambda Windy: 0 if Windy  else 1)

In [13]:
df.head()

Outlook Temp Humidity  Windy Play
0       0    2        1      0   No
1       0    2        1      1   No
2       1    2        1      0  Yes
3       2    1        1      0  Yes
4       2    0        0      0  Yes

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Outlook   14 non-null     object
 1   Temp      14 non-null     object
 2   Humidity  14 non-null     object
 3   Windy     14 non-null     int64 
 4   Play      14 non-null     object
dtypes: int64(1), object(4)
memory usage: 692.0+ bytes


In [15]:
# df.values將dataframe轉換為numpy ndarray
df[["Outlook","Temp","Humidity","Windy"]].values

array([[0, 2, 1, 0],
       [0, 2, 1, 1],
       [1, 2, 1, 0],
       [2, 1, 1, 0],
       [2, 0, 0, 0],
       [2, 0, 0, 1],
       [1, 0, 0, 1],
       [0, 1, 1, 0],
       [0, 0, 0, 0],
       [2, 1, 0, 0],
       [0, 1, 0, 1],
       [1, 1, 1, 1],
       [1, 2, 0, 0],
       [2, 1, 1, 1]], dtype=object)

In [16]:
columns = ["Outlook","Temp","Humidity","Windy"]
features = df[list(columns)].values
X = features.astype(np.int8)
y = targets = labels = df["Play"].values

In [17]:
X

array([[0, 2, 1, 0],
       [0, 2, 1, 1],
       [1, 2, 1, 0],
       [2, 1, 1, 0],
       [2, 0, 0, 0],
       [2, 0, 0, 1],
       [1, 0, 0, 1],
       [0, 1, 1, 0],
       [0, 0, 0, 0],
       [2, 1, 0, 0],
       [0, 1, 0, 1],
       [1, 1, 1, 1],
       [1, 2, 0, 0],
       [2, 1, 1, 1]], dtype=int8)

In [18]:
y

array(['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes',
       'Yes', 'Yes', 'Yes', 'No'], dtype=object)

In [19]:
clf = tree.DecisionTreeClassifier(criterion="entropy")  #注意max_depth,可能造成提早剪枝
clf.fit(X,y)

In [20]:
clf.score(X,y)

1.0

In [21]:
#overcast,mild,high,false
clf.predict([[1,1,1,1]])

array(['Yes'], dtype=object)

In [22]:
clf.predict_proba([[1,1,1,1]])

array([[0., 1.]])

In [23]:
#rain,mild,high,false
clf.predict([[2,1,1,1]])

array(['No'], dtype=object)

In [24]:
clf.predict_proba([[2,1,1,1]])

array([[1., 0.]])

In [25]:
target_names=np.array(['No','Yes'])

In [26]:
dot_data = tree.export_graphviz(clf,out_file=None,feature_names=columns,class_names=target_names,filled=True,rounded=True,special_characters=True)

In [27]:
graph = pydotplus.graph_from_dot_data(dot_data)
graph.write_pdf(r"c:\temp\Weather_PlayGolf.pdf")

True

In [28]:
clf.predict([[1,1,1,1]])

array(['Yes'], dtype=object)

In [29]:
clf.predict([[2,0,1,0]])

array(['Yes'], dtype=object)

In [30]:
clf_gini = tree.DecisionTreeClassifier(criterion="gini")  #注意max_depth,可能造成提早剪枝
clf_gini.fit(X,y)
target_names=np.array(['No','Yes'])
dot_data = tree.export_graphviz(clf_gini,out_file=None,feature_names=columns,class_names=target_names,filled=True,rounded=True,special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data)
graph.write_pdf(r"c:\temp\Weather_PlayGolf_gini.pdf")

True

In [31]:
dataframe = pd.read_csv(r'c:\pyml_scripts\chapter05_decisiontree\weather2.csv',names=['Outlook','Temp','Humidity','Windy','Play'])

In [32]:
dataframe.head()

Outlook  Temp  Humidity  Windy Play
0     Rainy    85        85  False   No
1     Rainy    80        90   True   No
2  Overcast    83        78  False  Yes
3     Sunny    70        96  False  Yes
4     Sunny    68        80  False  Yes

In [33]:
#將文字類別進行數值化
dataframe.Outlook[dataframe["Outlook"]=='Sunny']=0
dataframe.Outlook[dataframe["Outlook"]=='Overcast']=1
dataframe.Outlook[dataframe["Outlook"]=='Rainy']=2
dataframe["Windy"]=dataframe["Windy"].apply(lambda Windy: '0' if Windy  else '1')
y = targets = labels = dataframe["Play"].values
columns = ["Outlook","Temp","Humidity","Windy"]
features = dataframe[list(columns)].values.astype(np.int32)

In [34]:
dataframe.head()

Outlook  Temp  Humidity Windy Play
0       2    85        85     1   No
1       2    80        90     0   No
2       1    83        78     1  Yes
3       0    70        96     1  Yes
4       0    68        80     1  Yes

In [35]:
from sklearn import tree
clf2 = tree.DecisionTreeClassifier(criterion="gini")
X = features
clf2.fit(X,y)

DecisionTreeClassifier()

In [36]:
clf2.score(X,y)

1.0

In [37]:
target_names=np.array(['No','Yes'])

dot_data = tree.export_graphviz(clf2,out_file=None,feature_names=columns,class_names=target_names,filled=True,rounded=True,special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data)
graph.write_pdf(r"c:\temp\Weather_PlayGolf2.pdf")

True

In [38]:
clf2.predict([[1,85,80,1]])

array(['Yes'], dtype=object)

In [39]:
clf2.predict_proba([[1,85,80,1]])

array([[0., 1.]])

In [40]:
clf2.predict([[2,78,90,0]])

array(['No'], dtype=object)

In [41]:
clf2.predict_proba([[2,78,90,0]])

array([[1., 0.]])